#ifndef PARAMETER_ADDRESS_H_
#define PARAMETER_ADDRESS_H_
#include <MasterDefine.h>

#define PID_GAIN_VEL_ADDR_1     (DATAFLASH_START_ADDR + 0x00)
#define PID_GAIN_VEL_ADDR_2     (DATAFLASH_START_ADDR + 0x08)
#define PID_GAIN_ANG_VEL_ADDR_1 (DATAFLASH_START_ADDR + 0x10)
#define PID_GAIN_ANG_VEL_ADDR_2 (DATAFLASH_START_ADDR + 0x18)


#endif
