#ifndef PARAMETER_ADDRESS_H_
#define PARAMETER_ADDRESS_H_
#include <MasterDefine.h>

#define MACHINE_NAME_1          (DATAFLASH_START_ADDR + 0x00)
#define MACHINE_NAME_2          (DATAFLASH_START_ADDR + 0x08)
#define MACHINE_INFO_1          (DATAFLASH_START_ADDR + 0x10)
#define MACHINE_INFO_2          (DATAFLASH_START_ADDR + 0x18)
#define PID_GAIN_VEL_ADDR_1     (DATAFLASH_START_ADDR + 0x20)
#define PID_GAIN_VEL_ADDR_2     (DATAFLASH_START_ADDR + 0x28)
#define PID_GAIN_ANG_VEL_ADDR_1 (DATAFLASH_START_ADDR + 0x30)
#define PID_GAIN_ANG_VEL_ADDR_2 (DATAFLASH_START_ADDR + 0x38)


#endif
